In [1]:
import cv2
import numpy as np

## 图像的加、减、乘、除运算

In [4]:
# 加法运算

# 读取图片
iu = cv2.imread('./fig/iu.png')

jennie = cv2.imread('./fig/Jennie.png')

print(iu.shape)
print(jennie.shape)

# 加法要求两个图片大小一致
# 使用ndarray的切片，切出大小一样的图片
new_jennie = jennie[0:380, 0:380]
print(new_jennie.shape)

#加法，加法的效果是加起来如果超过255，统一变成255
new_img = cv2.add(iu, new_jennie)

cv2.imshow('new_img', new_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(380, 380, 3)
(1000, 1000, 3)
(380, 380, 3)


In [5]:
# 图片还可以和单个数字进行运算
# 超出255的数字，会被截断，相当于 % 255

iu += 100
print(iu[:2, :2])

cv2.imshow('iu', iu)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[15  5  5]
  [15  5  5]]

 [[15  5  5]
  [15  5  5]]]


In [7]:
# 减法运算
# 小于0，为0
iu -= 100
new_img1 = cv2.subtract(new_jennie, iu)

cv2.imshow('img1', new_img1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
# 乘法运算
iu -= 100
jennie -= 100
new_img2 = cv2.multiply(new_jennie, iu)

cv2.imshow('img2', new_img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# 除法运算
iu += 100
jennie += 200
new_img3 = cv2.divide(new_jennie, iu)

cv2.imshow('img3', new_img3)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 图像的融合

In [16]:
# 不是简单的加法，相当于对图像做了线性运算。
# new_img = w1 * img1 + w2 * img2 + bias

# 读取图片
iu = cv2.imread('./fig/iu.png')
jennie = cv2.imread('./fig/Jennie.png')

new_jennie = jennie[0:380, 0:380]

new_img4 = cv2.addWeighted(new_jennie, 0.3, iu, 0.7, +50)

cv2.imshow('img4', new_img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

## OpenCV的逻辑运算

In [28]:
# OpenCV中的逻辑运算就是对应位置元素进行与或非，异或运算

# 读取图片
iu = cv2.imread('./fig/iu.png')
jennie = cv2.imread('./fig/Jennie.png')

# 非
# iu_not = cv2.bitwise_not(iu)

# 与
# iu_and = cv2.bitwise_and(iu, new_jennie)

# 或
# iu_or = cv2.bitwise_or(iu, new_jennie)

# 异或
iu_xor = cv2.bitwise_xor(iu, new_jennie)

print(iu[:2, :2])
# print(iu_not[:2, :2])
# print(iu_and[:2, :2])
# print(iu_or[:2, :2])
# print(iu_xor[:2, :2])

# cv2.imshow('not', np.hstack((iu, iu_not)))
# cv2.imshow('and', np.hstack((iu, iu_and)))
# cv2.imshow('or', np.hstack((iu, new_jennie, iu_or)))
cv2.imshow('xor', np.hstack((iu, new_jennie, iu_xor)))

cv2.waitKey(0)
cv2.destroyAllWindows()

[[[171 161 161]
  [171 161 161]]

 [[171 161 161]
  [171 161 161]]]


## 图像的基本变换

### 缩放

In [1]:
import cv2
import numpy as np

In [1]:
from cvUtils import *

In [2]:
jennie = cv2.imread('./fig/Jennie.png')
iu = cv2.imread('./fig/iu.png')

print(jennie.shape)
print(iu.shape)

# resize
# new_jennie = cv2.resize(jennie, (380, 380)) # 插值缩放
new_jennie = cv2.resize(jennie, dsize=None, fx=0.5, fy=0.5)
print(new_jennie.shape)

# cv2.imshow('new_jennie', np.hstack((iu, new_jennie)))

# cv2.waitKey(0)
# cv2.destroyAllWindows()
# cv_show('new_jennie', np.hstack((iu, new_jennie)))

(1000, 1000, 3)
(380, 380, 3)
(500, 500, 3)


### 翻转

In [ ]:
# flip
jennie = cv2.imread('./fig/Jennie.png')

new_jennie = cv2.flip(jennie, 1)

cv2.imshow('new_jennie', np.hstack((jennie, new_jennie)))

cv2.waitKey(0)
cv2.destroyAllWindows()

### 旋转

In [ ]:
# rotate
jennie = cv2.imread('./fig/Jennie.png')

new_jennie = cv2.rotate(jennie, rotateCode=cv2.ROTATE_90_COUNTERCLOCKWISE)

cv2.imshow('new_jennie', new_jennie)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 仿射变换之平移

In [ ]:
jennie = cv2.imread('./fig/Jennie.png')
h, w, ch = jennie.shape

# 变换矩阵，最少是float32位
M = np.float32([[1, 0, 200], [0, 1, 0]])

# 平移操作
new_jennie = cv2.warpAffine(jennie, M, dsize=(w, h))

cv2.imshow('new_jennie', new_jennie)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 仿射变换之获取变换矩阵

In [ ]:
jennie = cv2.imread('./fig/Jennie.png')

h, w, ch = jennie.shape
    
M = cv2.getRotationMatrix2D((100, 100), 15, 1)

new_jennie = cv2.warpAffine(jennie, M, dsize=(w, h))

cv2.imshow('new_jennie', new_jennie)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# 通过三个点来确定变换矩阵
jennie = cv2.imread('./fig/Jennie.png')

h, w, ch = jennie.shape

src = np.float32([[200, 100], [300, 100], [200, 300]])
dst = np.float32([[100, 150], [360, 200], [280, 120]])

M = cv2.getAffineTransform(src, dst)
new_jennie = cv2.warpAffine(jennie, M, dsize=(w, h))

cv2.imshow('new_jennie', new_jennie)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 仿射变换之透视变换

In [ ]:
jennie = cv2.imread('./fig/Jennie.png')

# 获取变换矩阵
# src = np.float32([[100, 900], [800, ]])
# dst = ....

cv2.getPerspectiveTransform(src, dst)